[project]
name = "basics-of-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AL1US", email = "193784287+AL1US@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
]

[project.scripts]
basics-of-ml = "basics_of_ml:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
